version: '2.1'
orbs:
  node: circleci/node@4.2.0
jobs:
  pull_project:
    working_directory: ~/project
    executor:
      name: node/default
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - webapp
  test:
    working_directory: ~/project/webapp
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: my_workspace
      - node/install-packages:
          app-dir: ~/project/webapp
      - persist_to_workspace:
          root: ~/project
          paths:
            - webapp
      - run:
          command: npm run test
  build:
    working_directory: ~/project/webapp
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: my_workspace
      - node/install-packages
      - run:
          command: npm run build
workflows:
  test_my_app:
    jobs:
      - pull_project:
          name: pulled_project
      - test:
          name: tested
          requires:
            - pulled_project
      - build:
          name: built
          requires:
            - tested
