version: '2.1'
orbs:
  node: circleci/node@4.2.0
jobs:
  test:
    working_directory: ~/project/
    executor:
      name: node/default
    steps:
      - node/install-packages:
          app-dir: ~/project/webapp
      - run:
          working_directory: ~/project/webapp
          command: npm run test
  build:
    working_directory: ~/project/
    executor:
      name: node/default
    steps:

      - node/install-packages
      - run:
          working_directory: ~/project/webapp
          command: npm run build
workflows:
  test_my_app:
    jobs:
      - test
      - build
