version: '2.1'
orbs:
  node: circleci/node@4.2.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - cd webapp
      - node/install-packages
      - run:
          command: npm run test
workflows:
  test_my_app:
    jobs:
      - test
